services:
  web:
    build:
      context: .
      dockerfile: nginx.dockerfile

    # command pake --build klo gak, coment it! (auto dikasi nama image)
    image: custom_nginx:0.1

    container_name: web
    ports:
      - "1111:80"
    networks:
      - net_coba
  api:
    image: nginx:stable-alpine
    container_name: api
    ports:
      - "2222:80"
    volumes:
      - ./soon/:/usr/share/nginx/html/
    networks:
      - net_coba

networks:
  net_coba: