networks:
  laravel:

volumes:
  mysqlVol:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8500:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:9.2.0-oracle
    container_name: mysql2
    restart: unless-stopped
    
    ports:
      - "4306:3306"
    volumes:
      - mysqlVol:/var/lib/mysql

    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myphp2
    environment:
      PMA_HOST: mysql2
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    depends_on:
      - mysql
    ports:
      - "8899:80"
    environment:
      PMA_HOST: mysql2
      MYSQL_ROOT_PASSWORD: secret
      UPLOAD_LIMIT: 64M
    networks:
      - laravel

  npm:
    image: node:13.7
    container_name: mynpm
    volumes:
      - ./src:/var/www/html
    entrypoint: ['npm']

  composer:
    image: composer:2.8.5
    container_name: composer
    volumes:
      - ./src:/var/www/html
    entrypoint: ['composer']